# Form implementation generated from reading ui file '/home/nixgnauhcuy/My/tmp_git/WechatImgDatDecodeQt/src/main.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 379)
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pathLineEdit = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.pathLineEdit.setGeometry(QtCore.QRect(30, 20, 441, 32))
        self.pathLineEdit.setReadOnly(True)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.pathPushButton = QtWidgets.QPushButton(parent=self.centralWidget)
        self.pathPushButton.setGeometry(QtCore.QRect(480, 20, 91, 34))
        self.pathPushButton.setObjectName("pathPushButton")
        self.decodePushButton = QtWidgets.QPushButton(parent=self.centralWidget)
        self.decodePushButton.setGeometry(QtCore.QRect(30, 60, 541, 31))
        self.decodePushButton.setObjectName("decodePushButton")
        self.logPlainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralWidget)
        self.logPlainTextEdit.setGeometry(QtCore.QRect(30, 100, 541, 241))
        self.logPlainTextEdit.setObjectName("logPlainTextEdit")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WechatImgDatDecode"))
        self.pathPushButton.setText(_translate("MainWindow", "选择路径"))
        self.decodePushButton.setText(_translate("MainWindow", "转换"))
